# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "uas" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-666babaa-de49-4bd1-af4d-566699bc374b";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-666babaa-de49-4bd1-af4d-566699bc374b".device = "/dev/disk/by-uuid/666babaa-de49-4bd1-af4d-566699bc374b";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6468-DFE7";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/85df17fa-058f-4385-9b3a-6a5a1fd6047d";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
